# Site settings
title: "Sangoh Lee"
description: "Sangoh Lee's resume page"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Sangoh Lee"
resume_title:                   "Database Systems Postgraduate"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "solee@dblab.postech.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         "202 at Engineering building 2, POSTECH"

resume_header_contact_info:     "202 at Engineering building 2, POSTECH â€¢ solee@dblab.postech.ac.kr"
display_header_contact_info:    "true"

resume_header_intro: "<p>Hi, welcome to my website. I am a first-year Ph.D. student at  <a href='https://dslab.postech.ac.kr' target='_blank'>DSLab</a>@<a href='https://postech.ac.kr' target='_blank'>POSTECH</a>, under the supervision of Professor Wook-Shin Han. My primary research interests are graph data analytics (such as graph pattern cardinality estimation), efficient join processing, query optimization and AI4DB with deep learning. Recently, I received my bachelor's degree in electrical engineering at POSTECH. You can see my CV <a href='https://drive.google.com/file/d/1WhTteJ8sFroajh65qmefG6gwQNLZnhX0/view?usp=sharing' target='_blank'>here</a> for more information</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
#resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_education:       true
resume_section_experience:      true
resume_section_projects:        true
# resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
#resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Leesangoh"
  #resume_twitter_url:           "false"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/sangoh-lee-6aba1a23a/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://leesangoh.github.io"
 # resume_medium_url:            "https://medium.com/@jglovier" TO BE ADDED...
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
